name       : perl-ntlm
version    : 1.09
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/N/NB/NBEBOUT/NTLM-1.09.tar.gz : c823e30cda76bc15636e584302c960e2b5eeef9517c2448f7454498893151f85
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : This module implements the NTLM authentication mechanism.
description: |
    This module implements the NTLM authentication mechanism.  It can be used to perform NTLM style authentication for any desired protocol.
builddeps  :
    - perl-digest-hmac
    - perl-test-pod
rundeps    :
    - perl-digest-hmac
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
